Better (hopefully) check for non-existing modules and modules that fail to load due to compilation errors or errors in create()
Rev: server/base_server/module_support.pike:1.37