Added ST_MTIME, ST_CTIME and ST_SIZE macros (indexes in the array returned by file_stat()) since I am tired of including stat.h all the time, and stat[ ST_MTIME ] is more readable than stat[ 3 ].  Added push_compile_error_handler and pop_compile_error_handler, used by the configuration interface to redirect compilation errors (overrides the normal ErrorContainer class)
Rev: server/base_server/roxenloader.pike:1.115