ModuleInfo.instance() may throw the empty string. Report compilation errors for each roxen module instead of for each configuration.
Rev: server/base_server/configuration.pike:1.245